config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  mount RapidRack::Engine => '/auth'
  root to: 'welcome#index'
  get 'dashboard' => 'dashboard#index', as: 'dashboard'

  resources :providers do
    resources :roles do
      resources :members, controller: 'subject_role_assignments',
                          only: %i(new create destroy)
      resources :api_members, controller: 'api_subject_role_assignments',
                              only: %i(new create destroy)

      resources :permissions, only: %i(index create destroy)
    end

    resources :provided_attributes do
      get :select_subject, on: :collection
    end

    resources :invitations, only: %i(new create) do
      get :redeliver, on: :member
    end

    resources :api_subjects do
      member do
        get 'audits' => 'api_subjects#audits', as: 'audit'
      end
    end
  end

  resources :invitations, only: [] do
    collection do
      get 'complete' => 'invitations#complete'
      get ':identifier' => 'invitations#show', as: 'show'
      post ':identifier' => 'invitations#accept', as: 'accept'
    end
  end

  scope '/admin' do
    resources :invitations, only: %i(index)

    resources :available_attributes do
      collection do
        get 'audits' => 'available_attributes#audits', as: 'audit'
      end
      member do
        get 'audits' => 'available_attributes#audits', as: 'audit'
      end
    end

    resources :subjects, only: %i(index show destroy) do
      member do
        get 'audits' => 'subjects#audits', as: 'audit'
      end
    end

    resources :providers, only: [] do
      resources :permitted_attributes, only: %i(index create destroy)
    end
  end

  v1 = APIConstraints.new(version: 1, default: true)
  namespace :api, defaults: { format: 'json' } do
    scope 'subjects', constraints: v1 do
      get ':shared_token/attributes' => 'attributes#show',
          constraints: { shared_token: /[\w-]+/ }

      post 'attributes' => 'attributes#create'
    end
  end
end

app/models/api_subject_role_assignment.rb
class APISubjectRoleAssignment < ActiveRecord::Base
  audited comment_required: true, associated_with: :api_subject

  belongs_to :api_subject
  belongs_to :role

  valhammer

  validates :role, uniqueness: { scope: :api_subject }
end

app/controllers/api_subject_role_assignments_controller.rb
class APISubjectRoleAssignmentsController < ApplicationController
  before_action do
    @provider = Provider.find(params[:provider_id])
    @role = Role.find(params[:role_id])
  end

  def new
    check_access!("providers:#{@provider.id}:roles:grant")
    @api_subjects = APISubject.where.not(id: current_member_ids)
    @assoc = @role.api_subject_role_assignments.new
  end

  def create
    check_access!("providers:#{@provider.id}:roles:grant")
    audit_attrs = { audit_comment: 'Granted role from providers interface' }
    @assoc = @role.api_subject_role_assignments
             .create!(assoc_params.merge(audit_attrs))

    flash[:success] = creation_message(@assoc)

    redirect_to(provider_role_path(@provider, @role))
  end

  def destroy
    check_access!("providers:#{@provider.id}:roles:revoke")
    @assoc = @role.api_subject_role_assignments.find(params[:id])
    @assoc.audit_comment = 'Revoked role from providers interface'
    @assoc.destroy!

    flash[:success] = deletion_message(@assoc)

    redirect_to(provider_role_path(@provider, @role))
  end

  private

  def assoc_params
    params.require(:api_subject_role_assignment).permit(:api_subject_id)
  end

  def creation_message(assoc)
    "Granted #{@role.name} at #{@provider.name} to API Account: " \
      "#{assoc.api_subject.x509_cn}"
  end

  def current_member_ids
    @role.api_subject_role_assignments.map { |ra| ra.api_subject.id }
  end

  def deletion_message(assoc)
    "Revoked #{@role.name} at #{@provider.name} from API Account: " \
      "#{assoc.api_subject.x509_cn}"
  end
end

app/views/api_subject_role_assignments/new.html.erb
<%=
  breadcrumbs(
    { 'Providers' => providers_path },
    { @provider.name => provider_path(@provider) },
    { 'Roles' => provider_roles_path(@provider) },
    { @role.name => provider_role_path(@provider, @role) },
    'Add API Account'
  )
%>

<%= page_header(@provider.name, 'Grant Role to Subject') %>

<h3 class="ui header"><%= @role.name %></h3>

<%- if @api_subjects.present? %>
  <table class="ui striped compact table">
    <thead>
      <tr>
        <th>X.509 CN</th>
        <th>Description</th>
        <th/>
      </tr>
    </thead>
    <tbody>
      <%- @api_subjects.each do |api_subject| -%>
        <tr>
          <td><%= api_subject.x509_cn %></td>
          <td><%= api_subject.description %></td>
          <td class="right aligned">
            <%= form_for([@provider, @role, @assoc], url: provider_role_api_members_path(@provider, @role),
                                                     html: { class: 'inline' }) do |f| -%>

              <%= button_tag(name: 'api_subject_role_assignment[api_subject_id]',
                             value: api_subject.id, class: 'tiny green icon') do -%>
                <%= icon_tag('checkmark') %>
                Grant
              <%- end -%>
            <%- end -%>
          </td>
        </tr>
      <%- end -%>
    </tbody>
  </table>
<%- else %>
  <p>All available API accounts are already a member of this role.
<%- end %>