config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  mount RapidRack::Engine => '/auth'
  root to: 'welcome#index'
  get 'dashboard' => 'dashboard#index', as: 'dashboard'

  resources :providers do
    resources :roles do
      resources :members, controller: 'subject_role_assignments',
                          only: %i(new create destroy)
      resources :api_members, controller: 'api_subject_role_assignments',
                              only: %i(new create destroy)

      resources :permissions, only: %i(index create destroy)
    end

    resources :provided_attributes do
      get :select_subject, on: :collection
    end

    resources :invitations, only: %i(new create) do
      get :redeliver, on: :member
    end

    resources :api_subjects do
      member do
        get 'audits' => 'api_subjects#audits', as: 'audit'
      end
    end
  end

  resources :invitations, only: [] do
    collection do
      get 'complete' => 'invitations#complete'
      get ':identifier' => 'invitations#show', as: 'show'
      post ':identifier' => 'invitations#accept', as: 'accept'
    end
  end

  scope '/admin' do
    resources :invitations, only: %i(index)

    resources :available_attributes do
      collection do
        get 'audits' => 'available_attributes#audits', as: 'audit'
      end
      member do
        get 'audits' => 'available_attributes#audits', as: 'audit'
      end
    end

    resources :subjects, only: %i(index show destroy) do
      member do
        get 'audits' => 'subjects#audits', as: 'audit'
      end
    end

    resources :providers, only: [] do
      resources :permitted_attributes, only: %i(index create destroy)
    end
  end

  v1 = APIConstraints.new(version: 1, default: true)
  namespace :api, defaults: { format: 'json' } do
    scope 'subjects', constraints: v1 do
      get ':shared_token/attributes' => 'attributes#show',
          constraints: { shared_token: /[\w-]+/ }

      post 'attributes' => 'attributes#create'
    end
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  include Lipstick::AutoValidation

  audited comment_required: true, associated_with: :provider
  has_associated_audits

  belongs_to :provider

  has_many :permissions, dependent: :destroy
  has_many :subject_role_assignments, dependent: :destroy
  has_many :api_subject_role_assignments, dependent: :destroy

  has_many :subjects, through: :subject_role_assignments
  has_many :api_subjects, through: :api_subject_role_assignments

  valhammer
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action { @provider = Provider.find(params[:provider_id]) }

  def index
    check_access!("providers:#{@provider.id}:roles:list")
    @roles = @provider.roles.all
  end

  def new
    check_access!('admin:roles:create')
    @role = @provider.roles.new
  end

  def create
    check_access!('admin:roles:create')
    audit_attrs = { audit_comment: 'Created from providers interface' }
    @role = @provider.roles.create!(role_params.merge(audit_attrs))

    flash[:success] = "Created role #{@role.name} at #{@provider.name}"

    redirect_to([@provider, :roles])
  end

  def edit
    check_access!('admin:roles:update')
    @role = @provider.roles.find(params[:id])
  end

  def update
    check_access!('admin:roles:update')
    audit_attrs = { audit_comment: 'Updated from providers interface' }
    @role = @provider.roles.find(params[:id])
    @role.update_attributes!(role_params.merge(audit_attrs))

    flash[:success] = "Updated role #{@role.name} at #{@provider.name}"

    redirect_to([@provider, :roles])
  end

  def show
    check_access!("providers:#{@provider.id}:roles:read")
    @role = @provider.roles.find(params[:id])
  end

  def destroy
    check_access!('admin:roles:delete')
    @role = @provider.roles.find(params[:id])
    @role.audit_comment = 'Deleted from providers interface'
    @role.destroy!

    flash[:success] = "Deleted role #{@role.name} from #{@provider.name}"

    redirect_to([@provider, :roles])
  end

  private

  def role_params
    params.require(:role).permit(:name)
  end
end

app/views/roles/_form.html.erb
<%= form_for([@provider, @role], html: { id: 'role-form' }) do |f| -%>
  <%= field_block do -%>
    <%= f.label :name %>
    <%= f.text_field :name %>
  <%- end -%>

  <div class="line-of-buttons">
    <%= f.button(class: 'large green icon') do -%>
      <%= icon_tag('checkmark') %>
      <%= submit_label %>
    <%- end -%>

    <%= button_link_to(provider_roles_path(@provider), class: 'large icon') do -%>
      <%= icon_tag('cancel') %>
      Cancel
    <%- end -%>
  </div>

  <%= error_messages_tag %>
<%- end -%>

<%= validate_form('#role-form', :role) do -%>
  <%= auto_validate(@role, :name) %>
<%- end -%>

app/views/roles/edit.html.erb
<%=
  breadcrumbs(
    { 'Providers' => providers_path },
    { @provider.name => provider_path(@provider) },
    { 'Roles' => provider_roles_path(@provider) },
    { @role.name => provider_role_path(@provider, @role) },
    'Edit'
  )
%>

<%= page_header(@provider.name, 'Edit Role') %>

<h3 class="ui header"><%= @role.name %></h3>

<%= render(partial: 'form', locals: { submit_label: 'Save' }) %>

app/views/roles/index.html.erb
<%=
  breadcrumbs(
    { 'Providers' => providers_path },
    { @provider.name => provider_path(@provider) },
    'Roles'
  )
%>

<%= page_header(@provider.name, 'Roles') %>

<table class="ui striped compact table">
  <thead>
    <tr>
      <th>Name</th>
      <th class="center aligned">Users</th>
      <th class="center aligned">API Accounts</th>
      <th/>
    </tr>
  </thead>
  <tbody>
    <%- @roles.each do |role| -%>
      <tr>
        <td><%= role.name %></td>
        <td class="center aligned"><%= role.subjects.count %></td>
        <td class="center aligned"><%= role.api_subjects.count %></td>
        <td class="right aligned">
          <%- if permitted?("providers:#{@provider.id}:read") -%>
            <%= button_link_to([@provider, role], class: 'tiny icon') do -%>
              <%= icon_tag('users') %>
              Members
            <%- end -%>
          <%- end -%>

          <%- if permitted?('admin:roles:update') -%>
            <%= button_link_to([@provider, role, :permissions], class: 'tiny icon') do -%>
              <%= icon_tag('asterisk') %>
              Permissions
            <%- end -%>

            <%= button_link_to([:edit, @provider, role], class: 'tiny icon') do -%>
              <%= icon_tag('edit') %>
              Edit
            <%- end -%>
          <%- end -%>

          <%- if permitted?('admin:roles:delete') -%>
            <%= delete_button_tag([@provider, role]) %>
          <%- end -%>
        </td>
      </tr>
    <%- end -%>
  </tbody>
</table>

<%- if permitted?('admin:roles:create') -%>
  <div class="line-of-buttons">
    <%= button_link_to(new_provider_role_path(@provider), class: 'large green icon') do -%>
      <%= icon_tag('add') %>
      New Role
    <%- end -%>
  </div>
<%- end -%>

app/views/roles/new.html.erb
<%=
  breadcrumbs(
    { 'Providers' => providers_path },
    { @provider.name => provider_path(@provider) },
    { 'Roles' => provider_roles_path(@provider) },
    'New Role'
  )
%>

<%= page_header(@provider.name, 'New Role') %>

<%= render(partial: 'form', locals: { submit_label: 'Create' }) %>

app/views/roles/show.html.erb
<%=
  breadcrumbs(
    { 'Providers' => providers_path },
    { @provider.name => provider_path(@provider) },
    { 'Roles' => provider_roles_path(@provider) },
    @role.name
  )
%>

<%= page_header(@provider.name, 'View Role') %>

<h3 class="ui header"><%= @role.name %></h3>

<h4>Users</h4>
<table class="ui striped compact table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email Address</th>
      <th>Targeted ID</th>
      <th/>
    </tr>
  </thead>
  <tbody>
    <%- @role.subject_role_assignments.each do |assoc| -%>
      <tr>
        <td><%= assoc.subject.name %></td>
        <td><%= mail_to assoc.subject.mail %></td>
        <td><%= assoc.subject.targeted_id %></td>
        <td class="right aligned">
          <%- if permitted?("providers:#{@provider.id}:roles:revoke") %>
            <%- if(assoc.subject != @subject) %>
              <%= delete_button_tag(provider_role_member_path(@provider, @role, assoc), text: 'Revoke') %>
            <%- else %>
              <i class="icon ban"></i><strong>current account</strong>
            <%- end -%>
          <%- end -%>
        </td>
      </tr>
    <%- end -%>
  </tbody>
</table>

<h4>API Access</h4>
<table class="ui striped compact table">
  <thead>
    <tr>
      <th>x509 CN</th>
      <th>Email Address</th>
      <th class="center aligned">Functioning</th>
      <th/>
    </tr>
  </thead>
  <tbody>
    <%- @role.api_subject_role_assignments.each do |assoc| -%>
      <tr>
        <td><%= assoc.api_subject.x509_cn %></td>
        <td><%= mail_to assoc.api_subject.contact_mail %></td>
        <td class="center aligned">
          <%- if assoc.api_subject.functioning? -%>
            <%= icon_tag('green checkmark') %> Yes
          <%- else -%>
            <%= icon_tag('yellow warning sign') %> No
          <%- end -%>
        </td>
        <td class="right aligned">
          <%- if permitted?("providers:#{@provider.id}:roles:revoke") -%>
            <%= delete_button_tag(provider_role_api_member_path(@provider, @role, assoc),
                                  text: 'Revoke') %>
          <%- end -%>
        </td>
      </tr>
    <%- end -%>
  </tbody>
</table>

<div class="line-of-buttons">
  <%- if permitted?('admin:roles:update') -%>
    <%= button_link_to(edit_provider_role_path(@provider, @role), class: 'large icon') do -%>
      <%= icon_tag('edit') %>
      Edit
    <%- end -%>
  <%- end -%>

  <%- if permitted?("providers:#{@provider.id}:roles:grant") -%>
    <%= button_link_to(new_provider_role_member_path(@provider, @role), class: 'large green icon') do -%>
      <%= icon_tag('add') %>
      Add Subject
    <%- end -%>
  <%- end -%>

  <%- if permitted?("providers:#{@provider.id}:roles:grant") -%>
    <%= button_link_to(new_provider_role_api_member_path(@provider, @role), class: 'large green icon') do -%>
      <%= icon_tag('add') %>
      Add API Account
    <%- end -%>
  <%- end -%>
</div>